CA_index:
    path:     /
    defaults: { _controller: "AppBundle:Ca:index" }
    methods:  GET

CA_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Ca:show" }
    methods:  GET

CA_new:
    path:     /new
    defaults: { _controller: "AppBundle:Ca:new" }
    methods:  [GET, POST]

CA_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Ca:edit" }
    methods:  [GET, POST]

CA_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Ca:delete" }
    methods:  DELETE
