entreprises_index:
    path:     /
    defaults: { _controller: "AppBundle:Entreprises:index" }
    methods:  GET

entreprises_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Entreprises:show" }
    methods:  GET

entreprises_new:
    path:     /new
    defaults: { _controller: "AppBundle:Entreprises:new" }
    methods:  [GET, POST]

entreprises_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Entreprises:edit" }
    methods:  [GET, POST]

entreprises_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Entreprises:delete" }
    methods:  DELETE
