AppBundle\Entity\Ca:
    type: entity
    table: ca
    indexes:
        siret:
            columns:
                - siret
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        annee:
            type: date
            nullable: false
        modification:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
    manyToOne:
        siret:
            targetEntity: Entreprises
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                siret:
                    referencedColumnName: siret
            orphanRemoval: false
    lifecycleCallbacks: {  }
