AppBundle\Entity\Entreprises:
    type: entity
    table: entreprises
    uniqueConstraints:
        nom:
            columns:
                - nom
    id:
        siret:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nom:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        denomination:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        adresse:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        creation:
            type: date
            nullable: false
        directeur:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        modification:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
    lifecycleCallbacks: {  }
